'use strict';
(() => {
  const d = window.JCAREER_EVIDENCE;
  const $ = id => document.getElementById(id);
  const el = (tag, text, cls) => { const e = document.createElement(tag); if (text !== undefined) e.textContent = text; if (cls) e.className = cls; return e; };
  if (!d || !Array.isArray(d.controls) || d.controls.length !== 55) { $('page-title').textContent = '진단 데이터를 불러오지 못했습니다.'; return; }
  const state = {tab:'controls', query:'', facet:'', grade:''};
  const views = {controls:['체크리스트',d.controls],findings:['IaC Finding',d.findings],collection:['증적 수집표',d.collection],ai:['기존 AI 표본',d.existingAiEvidence || []]};
  const badge = (text, tone='') => el('span', text, 'badge '+tone);
  const controlById = new Map(d.controls.map(c=>[c.id,c]));
  [ ['55개','MAP 전체 항목','기술 27 · 관리 25 · 물리 3'],['37.0%','원본 이행 표기','10/27 · 운영효과성 미검증'],['51개 / 28종','IaC 경고 / 고유 규칙','원본 산출물 대조 대기'],['미평가','실제 AFTER','동일 조건 재검증 · 사람 판정 필요'] ].forEach(([value,label,note])=>{const x=el('div',undefined,'metric');x.append(el('p',label),el('strong',value),el('small',note));$('metrics').append(x);});
  const grades=[['취약 동작 관찰',4,'adverse'],['증거 공백',4,'gap'],['설계 근거 확보',6,'design'],['부분 관찰',13,'partial']];
  grades.forEach(([label,count,cls])=>{const b=el('button',undefined,cls);b.type='button';b.append(el('span',label),el('b',count+'개'));b.addEventListener('click',()=>{setTab('controls');state.grade=label;$('grade').value=label;render();$('records').scrollIntoView();});$('profile').append(b);});
  const svg = (name,attrs,text) => {const e=document.createElementNS('http://www.w3.org/2000/svg',name);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,String(v)));if(text!==undefined)e.textContent=text;return e;};
  const point=(i,r)=>[240+Math.cos(-Math.PI/2+i*Math.PI/3)*r,165+Math.sin(-Math.PI/2+i*Math.PI/3)*r];
  const poly=values=>values.map((v,i)=>point(i, v*27).join(',')).join(' ');
  const chart=$('radar');chart.append(svg('title',{},'기존 기술 27개 증거 수준. 실제 After는 미평가입니다.'));
  [1,2,3,4].forEach(n=>{chart.append(svg('polygon',{points:poly(Array(6).fill(n)),class:'radar-grid'}));chart.append(svg('text',{x:245,y:165-n*27+4,class:'radar-tick'},n));});
  d.radar.labels.forEach((label,i)=>{const end=point(i,108),p=point(i,139);chart.append(svg('line',{x1:240,y1:165,x2:end[0],y2:end[1],class:'radar-axis'}));chart.append(svg('text',{x:p[0],y:p[1]+4,'text-anchor':'middle',class:'radar-label'},label));});
  chart.append(svg('polygon',{points:poly(d.radar.target),class:'radar-target'}),svg('polygon',{points:poly(d.radar.baseline),class:'radar-current'}));
  d.radar.baseline.forEach((v,i)=>{const p=point(i,v*27);chart.append(svg('circle',{cx:p[0],cy:p[1],r:4,class:'radar-dot'}));const row=el('tr');[d.radar.labels[i],v.toFixed(2),'4.00*',(d.radar.controlIds[i]||[]).join(' · ')].forEach(x=>row.append(el('td',x)));$('radar-table').append(row);});
  d.notes.forEach(n=>$('notes').append(el('li',n)));
  d.sources.forEach(s=>{const box=el('div',undefined,'source-item');const a=el('a',s.id+' · '+s.title);try{const u=new URL(s.url);if(u.protocol==='https:'){a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';}}catch{}box.append(a,el('p',s.scope));$('source-links').append(box);});
  function options(items){$('facet').replaceChildren();items.forEach(([value,label])=>{const o=el('option',label);o.value=value;$('facet').append(o);});}
  function setTab(name){state.tab=name;state.facet='';state.grade='';$('grade').value='';$('grade-label').hidden=!['controls','collection'].includes(name);$('facet-label').textContent=name==='findings'?'심각도':name==='ai'?'프로필':'분야';options(name==='findings'?[['','전체 심각도'],...['Critical','High','Medium','Low'].map(x=>[x,x])]:name==='ai'?[['','전체 프로필'],['AS_IS','AS-IS'],['TO_BE','TO-BE']]:[['','전체 분야'],['기술','기술 27개'],['관리','관리 25개'],['물리','물리 3개'],['충돌','원문 충돌 3개']]);$('facet').value='';document.querySelectorAll('#tabs button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===name)));render();}
  Object.entries(views).forEach(([key,[label,rows]])=>{const b=el('button',label+' '+rows.length);b.type='button';b.dataset.view=key;b.setAttribute('aria-pressed','false');b.addEventListener('click',()=>setTab(key));$('tabs').append(b);});
  function selectedRows(){return views[state.tab][1].filter(row=>{const c=state.tab==='collection'?controlById.get(row.controls[0]):row;if(state.query&&!JSON.stringify(row).toLocaleLowerCase().includes(state.query))return false;if(state.facet){if(state.tab==='findings'&&row.severity!==state.facet)return false;if(state.tab==='ai'&&row.profile!==state.facet)return false;if(['controls','collection'].includes(state.tab)){if(state.facet==='충돌'?!c.conflict:c.category!==state.facet)return false;}}return !state.grade||!['controls','collection'].includes(state.tab)||c.evidenceGradeLabel===state.grade;});}
  function heading(labels){const tr=el('tr');labels.forEach(x=>{const th=el('th',x);th.scope='col';tr.append(th);});$('record-head').replaceChildren(tr);}
  function titleButton(text,fn,note){const td=el('td');const b=el('button',text,'row-title');b.type='button';b.addEventListener('click',fn);td.append(b);if(note)td.append(el('span',note,'cell-note'));return td;}
  function cell(value){const td=el('td');td.append(value instanceof Node?value:document.createTextNode(String(value??'—')));return td;}
  function render(){const tab=state.tab,rows=selectedRows();$('result-count').textContent=rows.length+' / '+views[tab][1].length+'개';$('record-body').replaceChildren();$('empty').hidden=rows.length!==0;$('record-table').hidden=rows.length===0;
    const notes={controls:'잠정 위험점수와 조치 순서는 별도입니다. 우선순위의 선행조건은 상세 대책에서 확인하세요. 실제 AFTER는 모두 미평가입니다.',findings:'팀원 IaC 실행 요약의 보고값입니다. 직접 재실행한 결과가 아니며 관련 통제 연결은 검토안입니다. 51개 경고를 최종 확정 취약점 수로 해석하지 않습니다.',collection:'아래는 항목별 수집 요청입니다. 목록에 있다는 이유로 자료 확보·조치 완료를 의미하지 않습니다. 기존 자료를 우선 대조합니다.',ai:'대표 5개 × 2프로필 × 기존 실행 2회의 20행입니다. 서로 다른 20개 시나리오가 아닙니다. LLM03의 실행별 판정 차이를 유지하며 외부 행동 요청은 실제 외부 실행 증거가 아닙니다.'};$('view-note').textContent=notes[tab];
    heading(tab==='controls'?['ID / 분야','항목','증거 수준','잠정 위험','우선순위','IaC 연결','실제 AFTER']:tab==='findings'?['원래 번호 / 규칙','IaC 경고','보고 심각도','요약 판정','관련 항목 검토안','출처 상태']:tab==='collection'?['ID / 분야','필요 증적','담당 역할','우선순위','수집 상태']:['실행 / 보고 시각','시나리오','프로필','보고 관찰 판정','보고 통제 상태','실제 AFTER']);
    rows.forEach(r=>{const tr=el('tr');if(tab==='controls'){tr.append(cell(r.id+' · '+r.category),titleButton(r.title,()=>showControl(r),r.conflict?'원문 충돌 · 사람 확인 대기':r.lifecycle),cell(badge(r.evidenceGradeLabel,r.evidenceGrade==='OBSERVED_ADVERSE_BEHAVIOR'?'critical':r.evidenceGrade==='EVIDENCE_GAP'?'line':'')),cell(String(r.riskScore)+' · '+r.riskGrade),cell(r.priority),cell(r.iacFindingRefs.length+'개'),cell(badge('미평가','line')));}else if(tab==='findings'){tr.append(cell(String(r.ordinal).padStart(2,'0')+' · '+r.ruleId),titleButton(r.title,()=>showFinding(r),'팀원 IaC 요약 · '+r.observedAt.slice(0,10)),cell(badge(r.severity,['Critical','High'].includes(r.severity)?'critical':'warn')),cell('보고된 '+r.status),cell(r.controlIds.join(' · ')),cell(badge('원본 대조 대기','warn')));}else if(tab==='collection'){const c=controlById.get(r.controls[0]);tr.append(cell(c.id+' · '+c.category),titleButton(c.title,()=>showControl(c),r.needed.slice(0,100)+(r.needed.length>100?'…':'')),cell(r.owner),cell(r.priority),cell(badge('수집 요청 / 새 실행 없음','warn')));}else{tr.append(cell(r.executionLabel+' · '+r.reportedStartedAt.replace('T',' ').replace('Z',' UTC')),titleButton(r.scenarioId,()=>showAi(r)),cell(r.profile==='AS_IS'?'AS-IS':'TO-BE'),cell(badge(r.reportedOutcome,r.reportedOutcome==='NOT_BLOCKED'?'critical':r.reportedOutcome==='INCONCLUSIVE'?'warn':'')),cell(r.reportedControlStatus),cell(badge('미평가','line')));}$('record-body').append(tr);});
  }
  function startDetail(id,title){$('detail-id').textContent=id;$('detail-title').textContent=title;$('detail-content').replaceChildren();}
  function section(title,items){const s=el('section',undefined,'detail-section');s.append(el('h3',title));const dl=el('dl');items.forEach(([k,v])=>{if(v===undefined||v===null||v==='')return;const row=el('div',undefined,'detail-row');row.append(el('dt',k),el('dd',Array.isArray(v)?v.join(' · '):String(v)));dl.append(row);});s.append(dl);$('detail-content').append(s);}
  function showControl(c){startDetail(c.id+' · MAP '+c.mapRow+'행 · '+c.category,c.title);$('detail-content').append(el('p','실제 AFTER 미평가 · '+c.evidenceStatus,'detail-banner'));section('현재 근거와 판정 범위',[['원본 표기',c.sourceStatus],['원문 충돌',c.conflict?'충돌 해소 전 사람 확인 필요':'해당 3건에 포함되지 않음'],['증거 수준',c.evidenceGradeLabel],['0점의 이유',c.evidenceZeroReason],['점수 근거',c.evidenceBasis],['잠정 위험',c.riskScore+' · '+c.riskGrade],['우선순위',c.priority+' · 위험점수와 별도인 실행 순서'],['IaC 연결',c.iacFindingRefs.length+'개 · 관련 항목 검토안']]);section('MEASURE · 무엇으로 확인할 것인가',[['측정 방법',c.metric],['범위·표본',c.sample],['수용 기준',c.acceptance],['필요 증적',c.evidenceNeeded],['수집 방법',c.evidenceMethod]]);section('MANAGE · 무엇을 바꿀 것인가',[['실무 대책',c.action],['솔루션',c.solution],['기능과 한계',c.solutionLimit],['담당 역할',c.owner],['선행조건',c.prerequisite]]);section('GOVERN · 누가 어떤 기준으로 결정할 것인가',[['정책 연결',c.policies],['정책·지침',c.govern]]);const related=d.findings.filter(f=>c.iacFindingRefs.includes(f.finding_ref));if(related.length){const s=el('section',undefined,'detail-section');s.append(el('h3','관련 IaC 경고 · 연결 검토안'));related.forEach(f=>{const b=el('button',String(f.ordinal).padStart(2,'0')+' · '+f.ruleId+' · '+f.title,'count-link');b.type='button';b.addEventListener('click',()=>showFinding(f));s.append(b,el('br'));});$('detail-content').append(s);}if(!$('detail').open)$('detail').showModal();}
  function showFinding(f){startDetail('IAC '+String(f.ordinal).padStart(2,'0')+' · '+f.ruleId,f.title);$('detail-content').append(el('p','팀원 실행 요약 · 원본 산출물 대조 대기 · 사람 판정 대기','detail-banner'));section('접수된 관찰과 한계',[['영속 Finding ID',f.finding_ref],['보고 검사 시각',f.observedAt],['도구 심각도',f.severity],['요약 표기',f.status+' (직접 재실행 아님)'],['관련 항목',f.controlIds],['연결 권한',f.mappingStatus],['해석의 한계',f.limitation],['다음 확인',f.action],['실제 AFTER','미평가']]);if(!$('detail').open)$('detail').showModal();}
  function showAi(r){startDetail(r.executionLabel+' · '+r.scenarioId,'기존 AI 표본의 보고된 판정');section('기존 검수 메타데이터',[['보고된 시작 시각',r.reportedStartedAt],['프로필',r.profile],['관찰 판정',r.reportedOutcome],['통제 상태',r.reportedControlStatus],['표본 범위',r.dataScope],['출처',r.sourceType],['한계',r.limitation],['실제 AFTER','미평가']]);$('detail-content').append(el('p','LLM03은 실행별 판정이 다릅니다. 외부 행동 요청 표지가 실제 외부 실행을 입증하지 않습니다. TO-BE는 독립된 운영 인프라의 개선 검증이 아닙니다.','detail-banner'));if(!$('detail').open)$('detail').showModal();}
  $('search').addEventListener('input',e=>{state.query=e.target.value.trim().toLocaleLowerCase();render();});$('facet').addEventListener('change',e=>{state.facet=e.target.value;render();});$('grade').addEventListener('change',e=>{state.grade=e.target.value;render();});$('reset').addEventListener('click',()=>{state.query='';$('search').value='';setTab(state.tab);});$('show-conflicts').addEventListener('click',()=>{state.query='';$('search').value='';setTab('controls');state.facet='충돌';$('facet').value='충돌';render();$('records').scrollIntoView();});$('close-detail').addEventListener('click',()=>$('detail').close());$('print').addEventListener('click',()=>window.print());setTab('controls');
})();
